name: deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests and Code Coverage Checks
        run: ./gradlew build

      - name: Rename Artifact
        run: cp build/libs/access-request-finder-0.0.1-SNAPSHOT.jar access-request-finder-${{ github.sha }}.jar

      - name: Save Artifact
        uses: actions/upload-artifact@master
        with:
          name: access-request-finder
          path: access-request-finder-${{ github.sha }}.jar

  fake-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@master
        with:
          name: access-request-finder

      - name: Fake Deploy
        run: ls access-request-finder*.jar
